### ISSUE TITLE
Regression in 2.6: get_form_list() caching ignores runtime changes to form_list (#291)

### ISSUE THREAD

**Issue by fsbraun** [jazzband/django-formtools#295]
### Summary

PR #291 ("Improved performance when using `condition_dict`") changed `WizardView.get_form_list()` to cache its result in `self._resolved_form_list`. The cache key (`_condition_dict_signature`) is derived **only from `condition_dict`** — it does not account for changes to `self.form_list` itself.

This is a behavioural regression. In 2.5.1 the docstring of `get_form_list()` explicitly stated:

> The form_list is always generated on the fly because condition methods could use data from other (maybe previous forms).

Any subclass that adjusts `self.form_list` at runtime (e.g. swapping a placeholder form for a dynamically built one) now silently receives a **stale** form class, because `get_form()` resolves the class via `self.get_form_list()[step]`.

This broke the test suite of [django-cms](https://github.com/django-cms/django-cms), whose wizard swaps in a dynamically constructed step-2 form.

### Affected versions

2.6 and 2.6.1 (works in 2.5.1).

### Minimal reproduction

```python
from django import forms
from formtools.wizard.views import SessionWizardView


class PlaceholderForm(forms.Form):
    pass


class RealForm(forms.Form):
    def __init__(self, *args, extra=None, **kwargs):
        super().__init__(*args, **kwargs)


class MyWizard(SessionWizardView):
    form_list = [("0", forms.Form), ("1", PlaceholderForm)]

    def get_form(self, step=None, data=None, files=None):
        if step is None:
            step = self.steps.current
        # Runtime substitution of the step-1 form.
        if step == "1":
            self.form_list["1"] = RealForm
        return super().get_form(step, data, files)

    def get_form_kwargs(self, step=None):
        kwargs = super().get_form_kwargs(step)
        if step == "1":
            kwargs["extra"] = "value"   # only RealForm accepts this
        return kwargs
```

When the wizard advances to step `"1"`:

- **2.5.1:** `get_form_list()` regenerates from `self.form_list`, so `RealForm` is used. Works.
- **2.6.1:** `get_form_list()` returns the cached list still containing `PlaceholderForm`, which is instantiated with the `extra` kwarg → `TypeError: __init__() got an unexpected keyword argument 'extra'`.

### Root cause

In 2.6's `get_form_list()`:

```python
condition_dict_signature = (
    id(self.condition_dict),
    tuple(sorted(self.condition_dict.items())),
)
if (hasattr(self, '_resolved_form_list') and
    self._condition_dict_signature == condition_dict_signature):
    return self._resolved_form_list.copy()
```

The signature reflects `condition_dict` but not `form_list`. The cache is invalidated after a valid step POST, but never when `form_list` itself is mutated within a request.

### Suggested fixes (any one)

1. Include `form_list` in the cache signature (e.g. `tuple(self.form_list.items())`).
2. Make the caching opt-in, or document that `form_list` must not be mutated after view init.
3. At minimum, note this behaviour change in the changelog — 2.6 advertised #291 as a pure performance improvement.

### Workaround (downstream)

Subclasses can override `get_form_list()` to perform the substitution there instead of mutating `self.form_list`, so the returned (copied) list always reflects the runtime state. This is what we did in django-cms.

**Comment by claudep** [comment]
@knyghty, could you have a look at this regression and propose a fix?

**Comment by knyghty** [comment]
Yes, hopefully today or tomorrow.

**Comment by Lukas253** [comment]
Also hitting this in `django-two-factor-auth`'s WebAuthn login flow —` LoginView.get_form` swaps in `WebauthnAuthenticationTokenForm` via `self.form_list[TOKEN_STEP] = method.get_token_form_class()`, but with 2.6.1 the cached `AuthenticationTokenForm` comes back from `get_form_list()`. Net effect for users: the WebAuthn JS (`form.media`) never loads on the token step, browsers don't surface any passkey prompt, and if the prompt does fire on a worker where the mutation already stuck, the assertion JSON gets POSTed into a TOTP RegexField and fails with `"at most 6 characters (it has 774)"`. Multiple gunicorn workers + the shared `as_view` form_list make it look random per request. Pinning `<2.6` restores the old behaviour cleanly

**Comment by lociii** [comment]
Also affected by this change as we use the wizard but dynamically add or remove steps depending on user selection in previous steps.

Even trying to override `get_form_list` and `get_cleaned_data_for_step` and always unset the cache does not work as `post` tries to remove the cache attributes even if they don't exist (as we removed them) which raises an `AttributeError`.

**Comment by knyghty** [comment]
@lociii it's strange that this is how you run into this problem because this is exactly the case where I needed this cache in the first place and it seems to work for us. I guess we must be doing it differently.

Also @fsbraun and @Lukas253 I've opened https://github.com/jazzband/django-formtools/pull/297 if you're able to test.
