### PR TITLE
Add form_list to cache signature

### LINKED ISSUE #295: Regression in 2.6: get_form_list() caching ignores runtime changes to form_list (#291)
### Summary

PR #291 ("Improved performance when using `condition_dict`") changed `WizardView.get_form_list()` to cache its result in `self._resolved_form_list`. The cache key (`_condition_dict_signature`) is derived **only from `condition_dict`** — it does not account for changes to `self.form_list` itself.

This is a behavioural regression. In 2.5.1 the docstring of `get_form_list()` explicitly stated:

> The form_list is always generated on the fly because condition methods could use data from other (maybe previous forms).

Any subclass that adjusts `self.form_list` at runtime (e.g. swapping a placeholder form for a dynamically built one) now silently receives a **stale** form class, because `get_form()` resolves the class via `self.get_form_list()[step]`.

This broke the test suite of [django-cms](https://github.com/django-cms/django-cms), whose wizard swaps in a dynamically constructed step-2 form.

### Affected versions

2.6 and 2.6.1 (works in 2.5.1).

### Minimal reproduction

```python
from django import forms
from formtools.wizard.views import SessionWizardView


class PlaceholderForm(forms.Form):
    pass


class RealForm(forms.Form):
    def __init__(self, *args, extra=None, **kwargs):
        super().__init__(*args, **kwargs)


class MyWizard(SessionWizardView):
    form_list = [("0", forms.Form), ("1", PlaceholderForm)]

    def get_form(self, step=None, data=None, files=None):
        if step is None:
            step = self.steps.current
        # Runtime substitution of the step-1 form.
        if step == "1":
            self.form_list["1"] = RealForm
        return super().get_form(step, data, files)

    def get_form_kwargs(self, step=None):
        kwargs = super().get_form_kwargs(step)
        if step == "1":
            kwargs["extra"] = "value"   # only RealForm accepts this
        return kwargs
```

When the wizard advances to step `"1"`:

- **2.5.1:** `get_form_list()` regenerates from `self.form_list`, so `RealForm` is used. Works.
- **2.6.1:** `get_form_list()` returns the cached list still containing `PlaceholderForm`, which is instantiated with the `extra` kwarg → `TypeError: __init__() got an unexpected keyword argument 'extra'`.

### Root cause

In 2.6's `get_form_list()`:

```python
condition_dict_signature = (
    id(self.condition_dict),
    tuple(sorted(self.condition_dict.items())),
)
if (hasattr(self, '_resolved_form_list') and
    self._condition_dict_signature == condition_dict_signature):
    return self._resolved_form_list.copy()
```

The signature reflects `condition_dict` but not `form_list`. The cache is invalidated after a valid step POST, but never when `form_list` itself is mutated within a request.

### Suggested fixes (any one)

1. Include `form_list` in the cache signature (e.g. `tuple(self.form_list.items())`).
2. Make the caching opt-in, or document that `form_list` must not be mutated after view init.
3. At minimum, note this behaviour change in the changelog — 2.6 advertised #291 as a pure performance improvement.

### Workaround (downstream)

Subclasses can override `get_form_list()` to perform the substitution there instead of mutating `self.form_list`, so the returned (copied) list always reflects the runtime state. This is what we did in django-cms.

### PR DESCRIPTION
**Pull request by knyghty**
Fixes #295

### CODE REVIEW

**Review by fsbraun — APPROVED** [review]
@knyghty Thank you so much for the quick fix. **I ran it against the code base of django CMS and it works fine!!** Also, it should keep the caching feature that can be expensive if DB access is needed (not in django CMS' case).

Two (very) small nits, none blocking:

  1. `id(self.form_list)` seems redundant to me given `tuple(self.form_list.items())` — the items tuple already detects both in-place   mutation and replacement-with-different-content. `id` only adds the "replaced with an equal-content dict" case. It's cheap and harmless, but a one-line comment explaining the split (`id` = identity swap, `items()` = content/mutation) would save the next reader a moment.
  2. Sorting asymmetry: `condition_dict` uses `tuple(sorted(...))` while `form_list` is unsorted. Unsorted is actually more correct here since form_list is order-sensitive — just looks accidental next to the sorted neighbor, so maybe a brief comment to signal it's intentional.

**Comment by tomasserravento** [comment]
Hey, thank you so much for this. I can confirm I updated to 2.6.1 and my form broke because it ignores runtime changes to the form_list, I hope this gets merged soon!

**Comment by claudep** [comment]
@knyghty, do you think it's worth amending your patch after @fsbraun comments?

**Comment by knyghty** [comment]
I'll look into it

**Comment by knyghty** [comment]
Both `id()`s seem redundant with the new code so I've removed that, and added a comment about the sorting.

@claudep feels ready to me.

**Comment by knyghty** [comment]
CI failures are unrelated, I have fixed in #300
